language: python

before_install:
- pip install -r requirements.txt
 
deploy:
   provider: cloudfoundry
   username: ravi218@gmail.com
   password: Year@2018
   api: https://api.run.pivotal.io
   organization: ravi218
   space: development
