language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -U pytest
script: pytest
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: ravi218@gmail.com
  password:
    secure: dvWJl1bhXqBcFWC15ILZE37KXrw1Eka8QAG9MGUGz1y8a94fm7pQYlUZQxPBJ3qIzpOBSb67wYVIVvnJdV9tIqJp8pA9H5m7oEn8M6ZuUUMCuTUBI4RTsoqGvZSO4Z1dJYpUrZyCKexvF2VcjCcB6BHd+DmzihzITBNTAWnxrsRiAiZj4GgwkJIFB43owMhhK7e5eoIMUJW0DIR1TTLRi77p3gzeJVPyIu7oS9I0tKM7mAg3kCsckbDo7bqSqfaPEWGkiU36zg+dKQyQPL+d+uW/jOIM0PM1IyXqfM61EmRRytVn1kTCudp2PSBPGurGTosCfU75QotChSV9x0NO40o05ySVXc9mChwCG9LrOLtX3tNlQlznbCUmmErOcZ5i5P3qfQDRBmDqucDTOyYFlrVQxv0nAKX92P+StSN5qXnvPQvnlX7KKblj/vto30jzy1dAEHtJhIu8l5wTX30L7EVWxn5/EkRNTDYBC3SvEi7TXzU7fo6XZRwSbqxpNVJyeXNmpA89oPyAv18xAQienPOlvlPpAae12dcAgVAnJjRuFcMaveVrBUyTRBheWpTJXzzAnSRBw1ZewHhu1mtsnU2Ttb2mMMTd+leJWBJsVOfiyjWr9EU/N0Bb4QqREcoFPL8YNtbGJjtzdcCdoJGEysQ3gEVYGUjrKH1X6qPSxuw=
  organization: ravi218
  space: development
  on:
    repo: rs975g/Mendix-Assignment
