language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -U pytest
script: pytest
deploy:
  provider: cloudfoundry
  username: ravi218@gmail.com
  password:
    secure: p1X2FAgJ0lAwNxuxa+fg9AVWbkvKRhUbPx0DBZIXnf//MjoXKOF+N9v4W3YJ5D4wnc1SRNqoMvTnQqky3B99C5TJvm022SAtlXdphjpvu+TD779NhS18YieE7ZSVAgbtZz1s2DXegkeYEn4jBMY2YFWleXOph47u/dv/mX6A+GRA3PMNyf96RWtZHSJuXmWU9i+tF6hDkjU1t/C8IpvI/4rmaebGn+a7g9yL63er3vWbJN+g4s++IxAzlIY2vvfzcRJZnim3NbUjeZg59oyfCs56O2wsAwj/z7loQyUJ3bNXPHxDKLr/qwOQAg53fJr90AobyX4yniAdcvjMx6wocayl2VUM0e+EM21LCgJ413inhAD8q9o6p9B0aBwablqmA7YWe3oKcp9KtbrTsZzTMSZnWt7lFEVKiPy+H8eC27fjHHjstdo4j74zFbBp0E7qqm2m15IaWBmdhxEM33PqddB0evMYiibCZvrFaE8xDzc9yvNCGEX1sgecWH1aBS37Z6p7iVEoQMgsrpnfhd7D3PzSfo+zroeL/t8owHskxu/Uglrm7UtWR9svNWZxnRSemiobPbiBAlx2W+ByxVsIp6xe/H8cBGG0ehqpgoEwnNBbpnqUTwVMrSAJP+qxpIdHuyFQ11dk4oQqEXyD257ndE8G5XIceGwChaH1u/xBYow=
  api: https://api.run.pivotal.io
  organization: ravi218
  space: development
