language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -U pytest
script: pytest
deploy:
  provider: cloudfoundry
  username: ravi218@gmail.com
  password:
    secure: BU3+2iYVxGi+OqQAJr8xtB/FYuFoXKlAfXyN6hSL7Zphb28oWHw6yrgZQTXE8feCv/Rd6Nm6eQZ41c5Uul2RHd8V696xxdunFgDU7xb0/Z8K/34DkROvjXACgsl2ryu/sh6qJwWnOuZw6mAWNyk3hbORMPA7HXvCQ4jea6ohKyDWmeh7LR3LxzoQqs3RrV0zvRt6QwWatatHK/c8ixqPwGaIMVroka30QlEEmbQsLGXu1V5ng5WpniaP1VNbR63rrk1TrX+Yr1hycdAq7qy9DAEMYK7v/YMAE+g9IGbTBYpKoMr4iBGKBvvqzA7r/wMWwd/ZGzORzDEOpqKBaMleWpE/U4+pcjGCagw12Ty+m/CCZQ/kyEceVtr7o4TuYxT/gO4AcL8t9rM2nrllUQ04TyY/oqxPkg0wTsL5fdNxYSsDJxqjoTJyl7H123yjxxhSMUlYLzFJzOsEv9RLFnTe8HP8Lpm+Dj6FgEa/sf6twP2nxc2KOEXUDJ8EwliQ2mO32gkFdsoX97G5/8B6KSMGprYYP3NEU3dYsWIpxuB5KODZW/OScXdZxZj5HuraP0eoLBWkC2dmjU1F5IdscvUvdFxvyyvb4/+3mezCdlBITE6NGHFN+szdSFRJiekG4jLkDP0cWw4C2YONHAfV5yIuBzaGy+roJOVeRP555BguHbM=
  api: https://api.run.pivotal.io
  organization: ravi218
  space: development
