language: python
python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install -U pytest

script: pytest

deploy:
  provider: cloudfoundry
  username: ravi218@gmail.com
  password: Year@2016
  api: https://api.run.pivotal.io
  organization: ravi218
  space: development
